site_name: A Proximal Projection Method for Stable Linearly Constrained Optimization
site_description: Documentation for code used in the paper for the Proximal Projection (PP) algorithm.

extra_css:
  - stylesheets/extra.css
 
plugins:
  - mkdocstrings 
  - mkdocs-jupyter:
      include_source: True
      include: ["*.ipynb"]
  - search
    
  
theme:
  name: material
  custom_dir: docs/overrides  
  logo: assets/logo-v3-light.png
  favicon: assets/logo-v3-dark.png
  palette:
    scheme: default  
  language: en
  features:
    - navigation.tabs 
    - navigation.tabs.sticky
    - navigation.indexes   
    - navigation.footer     
    - header.autohide

extra:
  homepage: https://typal.academy
  social:
    - icon: simple/substack
      link: https://typalacademy.com
    - icon: fontawesome/brands/stack-exchange
      link: https://math.stackexchange.com/users/1327585/howard
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/howard-heaton/ 
    - icon: fontawesome/brands/x-twitter
      link: https://x.com/TypalAcademy     
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@TypalAcademy         

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tasklist:
      custom_checkbox: true   
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
    - 'Home': index.md


copyright: |
  &copy; 2024 <a href="https://typal.academy"  target="_blank" rel="noopener">Typal Academy.</a> 
  All Rights Reserved.
  <br> 
  <a href="https://typal.academy/terms-of-service">Terms of Service </a> &nbsp; &nbsp;
  <a href="https://typal.academy/privacy">Privacy Policy</a>
