[tool.poetry]
name = "proximal-projection"
version = "0.1.0"
description = "Numerical examples using proximal projection algorithm"
authors = ["Howard Heaton <research@typal.academy>"]
packages = [{ include = "basis_pursuit", from = "src" }]

[project]
name = "proximal-projection"
version = "0.1.0"
description = "A brief description of your module"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {text = "MIT"}
dependencies = ["requests"]
readme = "README.md"
requires-python = ">=3.6"


[tool.poetry.dependencies]
python = ">=3.12"
pydantic = "^2.10.6"
numpy = "^2.2.4"


[tool.poetry.group.dev.dependencies]
black = "^23.1.0"
flake8 = "^7.1.2"
mypy = "^1.4.0"
pylint = "^3.3.5"


[tool.black]
line-length = 100
target-version = ['py312']


[tool.pylint."MESSAGES CONTROL"]
disable = ["invalid-name", "anomalous-backslash-in-string"]


[tool.mypy]
files = ["src/"]
disallow_untyped_calls = true
check_untyped_defs = true
warn_return_any = true
ignore_missing_imports = true


[tool.poetry.scripts]
basis_pursuit_experiment = "basis_pursuit.basis_pursuit_experiment:main"
