name: docs site
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy code from ./src to ./docs
        run: cp -r ./src/*.ipynb ./docs/notebooks/
      - name: Commit files
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Copy notebooks from ./src to ./docs" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install pillow cairosvg             
      - run: pip install mkdocs-material 
      - run: pip install 'mkdocstrings[crystal,python]'   
      - run: pip install mkdocs-jupyter
      - run: mkdocs gh-deploy --force
