name: copy notebooks to docs
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Copy code from ./src to ./docs
        run: cp -r ./src/*.ipynb ./docs/notebooks/

      - name: Check if there are any changes
        id: verify_diff
        run: |
          git diff --quiet . || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Commit files
        if: steps.verify_diff.outputs.changed == 'true'      
        run: |
          git add .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Copy notebooks from ./src to ./docs" -a

      - name: Push changes
        if: steps.verify_diff.outputs.changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   
